<?php

namespace AppBundle\Repository;

/**
 * UniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class UserRepository extends \Doctrine\ORM\EntityRepository
{

    function findAllUsers()
    {
        return $this->getEntityManager()
            ->createQueryBuilder('u')
            ->select('u.id, u.email, u.username, u.fullName')

            ->from('AppBundle:User', 'u')
            ->getQuery()
            ->getResult();
    }

    function checkIfUserExist($service, $userId)
    {
        $searched_user = $this->findBy(array(
            $service . "Id" => $userId,
        ));

        if (count($searched_user) == 1) {
            return $searched_user;
        } else {
            return false;
        }
    }

    function checkIfNewUsernameExist($username)
    {
        $searched_user = $this->findBy(array(
            'username' => $username
        ));
        if (count($searched_user) == 1) {
            return true;
        } else {
            return false;
        }
    }

    function checkIfUsernameExist($given_user, $own_username)
    {

        $searched_user = $this->findBy(array(
            'username' => $given_user->getUsername(),
        ));


//        var_dump($searched_user);

        if (count($searched_user) == 1 && $own_username != $searched_user[0]->getUsername()) {
//            echo "paise";
            return true;
        } else {
//            echo "pai nai";
            return false;
        }

    }

    function checkIfUsernameExistByUsername($given_user_name, $own_username)
    {

        $searched_user = $this->findBy(array(
            'username' => $given_user_name,
        ));
        if (count($searched_user) == 1 && $own_username != $searched_user[0]->getUsername()) {
            return true;
        } else {
            return false;
        }

    }

    function checkIfNewEmailExist($email)
    {
        $searched_user = $this->findBy(array(
            'email' => $email,
        ));
        if (count($searched_user) == 1) {
            return true;
        } else {
            return false;
        }
    }

    function checkIfEmailExist($given_user, $own_mail)
    {
        $searched_user = $this->findBy(array(
            'email' => $given_user->getEmail(),
        ));


//        var_dump($searched_user);

        if (count($searched_user) == 1 && $own_mail != $searched_user[0]->getEmail()) {
//            echo "paise";
            return true;
        } else {
//            echo "pai nai";
            return false;
        }
    }

    function checkIfEmailExistByEmail($given_email, $own_email)
    {
        $searched_user = $this->findBy(array(
            'email' => $given_email,
        ));
        if (count($searched_user) == 1 && $own_email != $searched_user[0]->getEmail()) {
            return true;
        } else {
            return false;
        }
    }
}
