<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishListRepository extends EntityRepository
{
    function checkIfAlreadyAddedToWishList($userId,$bookId){
       $data =  $this->getEntityManager()
            ->createQueryBuilder('w')
            ->select('w.id')

            ->from('AppBundle:WishList', 'w')
            ->andwhere('w.user = :user')
            ->andwhere('w.book = :book')

            ->setParameter('book', $bookId)
            ->setParameter('user', $userId)
            ->getQuery()
            ->getResult();

        if(count($data)>0){
            return true;

        }else{
            return false;

        }
    }
}
