<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishListRepository extends EntityRepository
{
    function checkIfAlreadyAddedToWishList($userId,$bookId){
       $data =  $this->getEntityManager()
            ->createQueryBuilder('w')
            ->select('w.id')

            ->from('AppBundle:WishList', 'w')
            ->andwhere('w.user = :user')
            ->andwhere('w.book = :book')

            ->setParameter('book', $bookId)
            ->setParameter('user', $userId)
            ->getQuery()
            ->getResult();

        if(count($data)>0){
            return true;

        }else{
            return false;

        }
    }

    function removeWishListItem($id){

    }

//    function getMyWishListBooks($userId){
//        return $this->getEntityManager()
//            ->createQueryBuilder('w')
//            ->select("b.id as bookId,
//                      b.bookIsbn10,
//                      b.bookIsbn13,
//                      b.bookTitle,
//                      b.bookDirectorAuthorArtist,
//                      b.bookEdition,
//                      b.bookPublisher,
//                      b.bookPublishDate,
//                      b.bookBinding,
//                      b.bookPage,
//                      b.bookImage,
//                      u.username as sellerUsername,
//                      bd.bookContactHomeNumber as sellerHomeNumber,
//                      bd.bookContactCellNumber as sellerCellNumber,
//                      bd.bookContactEmail as sellerEmail,
//                      bd.id as bookDealId,
//                      bd.bookPriceSell,
//                      bd.bookCondition,
//                      bd.bookIsHighlighted,
//                      bd.bookHasNotes,
//                      bd.bookComment,
//                      bd.bookContactMethod,
//                      bd.bookPaymentMethodCaShOnExchange,
//                      bd.bookPaymentMethodCheque,
//                      bd.bookIsAvailablePublic,
//                      bd.bookAvailableDate,
//                      bd.bookStatus,
//                      bd.bookViewCount,
//                      IDENTITY(bd.buyer) AS buyerId,
//                      c.campusName,
//                      un.universityName,
//                      s.stateName,
//                      s.stateShortName,
//                      co.countryName,
//                      con.id as contactId,
//                      con.contactDateTime,
//                      con.buyerHomePhone,
//                      con.buyerCellPhone
//                      ")
//
//            ->from('AppBundle:WishList', 'w')
//            ->innerJoin('AppBundle:Book', 'b', 'WITH', 'w.book = b.id')
//
//            ->andwhere('w.user = :userId')
//            ->setParameter('userId', $userId)
//            ->getQuery()
//            ->getResult();
//    }
}
