bookimage:
    path:     /
    defaults: { _controller: "AppBundle:CRUD/BookImage:index" }

bookimage_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CRUD/BookImage:show" }

bookimage_new:
    path:     /new
    defaults: { _controller: "AppBundle:CRUD/BookImage:new" }

bookimage_create:
    path:     /create
    defaults: { _controller: "AppBundle:CRUD/BookImage:create" }
    methods:  POST

bookimage_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CRUD/BookImage:edit" }

bookimage_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:CRUD/BookImage:update" }
    methods:  [POST, PUT]

bookimage_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CRUD/BookImage:delete" }
    methods:  [POST, DELETE]
