newsletter:
    path:     /
    defaults: { _controller: "AppBundle:CRUD/Newsletter:index" }

newsletter_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CRUD/Newsletter:show" }

newsletter_new:
    path:     /new
    defaults: { _controller: "AppBundle:CRUD/Newsletter:new" }

newsletter_create:
    path:     /create
    defaults: { _controller: "AppBundle:CRUD/Newsletter:create" }
    methods:  POST

newsletter_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CRUD/Newsletter:edit" }

newsletter_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:CRUD/Newsletter:update" }
    methods:  [POST, PUT]

newsletter_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CRUD/Newsletter:delete" }
    methods:  [POST, DELETE]
