star:
    path:     /
    defaults: { _controller: "AppBundle:CRUD/Star:index" }

star_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CRUD/Star:show" }

star_new:
    path:     /new
    defaults: { _controller: "AppBundle:CRUD/Star:new" }

star_create:
    path:     /create
    defaults: { _controller: "AppBundle:CRUD/Star:create" }
    methods:  POST

star_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CRUD/Star:edit" }

star_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:CRUD/Star:update" }
    methods:  [POST, PUT]

star_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CRUD/Star:delete" }
    methods:  [POST, DELETE]
