state:
    path:     /
    defaults: { _controller: "AppBundle:CRUD/State:index" }

state_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:CRUD/State:show" }

state_new:
    path:     /new
    defaults: { _controller: "AppBundle:CRUD/State:new" }

state_create:
    path:     /create
    defaults: { _controller: "AppBundle:CRUD/State:create" }
    methods:  POST

state_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:CRUD/State:edit" }

state_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:CRUD/State:update" }
    methods:  [POST, PUT]

state_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:CRUD/State:delete" }
    methods:  [POST, DELETE]
